// import the createSlice function from Redux Toolkit
import { createSlice } from '@reduxjs/toolkit';

// define the initial state of the user slice
const initialState = {
  userId: null,
};

// create a slice of the Redux store for the user state
const userSlice = createSlice({
  name: 'user', // specify the name of the slice
  initialState, // set the initial state
  reducers: {
    // define the action to set the user ID
    setUserId: (state, action) => {
      state.userId = action.payload; // update the user ID in the state
    },
  },
});

// export the action creators generated by createSlice
export const { setUserId } = userSlice.actions;

// export the reducer function generated by createSlice
export default userSlice.reducer;
